AWSTemplateFormatVersion: "2010-09-09"
Description: Template to create an S3 bucket

Resources:
  MyS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: 'kojadha-bucket-11/21/2024' # Replace with a unique name
      
